export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const ADD_BUN = "ADD_BUN";
export const CONSTRUCTOR_REMOVE_ITEM = 'CONSTRUCTOR_REMOVE_ITEM';
export const CONSTRUCTOR_UPDATE = 'CONSTRUCTOR_UPDATE';
export const CONSTRUCTOR_TOTALSUM = 'CONSTRUCTOR_TOTALSUM';
export const CONSTRUCTOR_RESET = 'CONSTRUCTOR_RESET';


